### ISSUE TITLE
[Meta] Gator's features to port with Conda Store

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#145]
Below are listed all the features from Gator, that need to be adapted to use with Conda Store. 
They are grouped by main category. For the priorities, [check the project](https://github.com/Quansight/gator/projects/1) 

- Environments : 
  - [ ]  [List environments]( https://github.com/Quansight/gator/issues/6)
  - [ ]  [Create environment]( https://github.com/Quansight/gator/issues/7)
  - [ ]  [Remove environment](https://github.com/Quansight/gator/issues/16)
  - [ ]  [Clone environment](https://github.com/Quansight/gator/issues/17)
  - [ ]  [Export environment](https://github.com/Quansight/gator/issues/18)
  - [ ]  [Import environment](https://github.com/Quansight/gator/issues/19)
  
- list of packages : 
  - [ ]  [List installable packages of a given env]( https://github.com/Quansight/gator/issues/8)
  - [ ]  [List installed packages of a given env]( https://github.com/Quansight/gator/issues/9)
  - [ ]  [List updatable packages of a given env](https://github.com/Quansight/gator/issues/12)
  - [ ]  [Filter a list of packages with the search field](https://github.com/Quansight/gator/issues/13)
  
- Packages : 
  - [ ]  [install packages in a given env](https://github.com/Quansight/gator/issues/10)
  - [ ]  [Remove a package from a given env](https://github.com/Quansight/gator/issues/11)
  - [ ]  [Change a package version](https://github.com/Quansight/gator/issues/14)
  - [ ]  [Update all packages](https://github.com/Quansight/gator/issues/15)

**Comment by costrouc** [comment]
Closing as new ui https://github.com/quansight/conda-store-ui is now being used
