### ISSUE TITLE
:runner:  Sprints meta-issue

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#353]
This weekend is [the SciPy 2022 sprints](https://www.scipy2022.scipy.org/sprints) and if you would like to contribute to conda-store, learn how to deploy conda-store, or learn more about the project you're in the right place. How this works:

 - Talk to Chris about which of the issues below you might work on, and we'll reserve it (check the box)
 - Fix the issue, make a PR, and iterate on it.
 - PR gets merged, celebrate!

conda-store issues:
 - [x] #343 
 - [x] https://github.com/Quansight/conda-store/issues/305
 - [x] https://github.com/Quansight/conda-store/issues/302
 - [x] https://github.com/Quansight/conda-store/issues/288
